title: Неидеальный код
email: spam81@bk.ru
description: >-
  Не надо стремиться к идеальному коду. Пусть твой код будет понятным, эффективным и, по возможности, красивым!
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
