title: Неидеальный код
email: spam81@bk.ru
description: >-
  Не надо стремиться к идеальному коду. Пусть твой код будет понятным, эффективным и, по возможности, красивым!
baseurl: ""
url: ""
#twitter_username: jekyllrb
#github_username:  jekyll
markdown: kramdown
kramdown:
  parse_block_html: true
theme: minima
plugins:
  - jekyll-feed
